import subprocess


def generate_tsp_file(filename, cities):
    with open(filename, 'w') as f:
        # Write the header
        f.write('NAME: {}\n'.format(filename))
        f.write('COMMENT: {}\n'.format('TSP file generated by Python'))
        f.write('TYPE: TSP\n')
        f.write('DIMENSION: {}\n'.format(len(cities)))
        f.write('EDGE_WEIGHT_TYPE: EUC_2D\n')
        # Write the city coordinates
        f.write('NODE_COORD_SECTION\n')
        for i, city in enumerate(cities):
            f.write('{} {} {}\n'.format(i + 1, city[0], city[1]))

        # Write the footer
        f.write('EOF\n')


def generate_parameter_file(output_filename):
    parameters = [
        "PROBLEM_FILE = tsp_file.tsp",
        "MOVE_TYPE = 5",
        "PATCHING_C = 3",
        "PATCHING_A = 2",
        "RUNS = 1",
        "TOUR_FILE = lkh_output.tour"
    ]
    with open(output_filename, 'w') as f:
        f.write('\n'.join(parameters))


def testmain():
    subprocess.run(['./LKH', 'pr2392.par'])
